### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by NerdyDJ** [Chauvet-Pro/WELLCOM_Flarecon#5]
### Contact Details

brent@djbrentschmidt.com

### Well Com or Flarecon

Flarecon

### What happened?

A bug happened! The light scene I thought I had programmed either stalled or couldn’t keep up with what I was doing in the app

### What Phone/Tablet are you seeing the problem on?

Apple

### Phone/Tablet Model

```shell
Phone
```

### Phone/Tablet software version

```shell
15.5
```

**Comment by dgooch5200** [comment]
@NerdyDJ  if possible, can you take a video of this?

**Comment by dgooch5200** [comment]
No reply closed.
