### ISSUE TITLE
[Bug]:  Flarecon App not connecting to FlareCON Air 2

### ISSUE THREAD

**Issue by iMDJace** [Chauvet-Pro/WELLCOM_Flarecon#6]
### Contact Details

aldwin@imobiledjs.com

### Well Com or Flarecon

Flarecon

### What happened?

The Flarecon app is having a hard time connecting to the FlareCON Air 2 device.  The FlareCON Air 2 has been Factory Reset, and on the iPhone, CHAUVETDJ is selected as the WiFi.  The WiFi icon appears at the top next to the battery indicator showing it's connected.  But when opening the FlareCon App, in the Settings, the Input Mode still appears as N/A.   There's no other indication that it's connected or not.

### What Phone/Tablet are you seeing the problem on?

Apple

### Phone/Tablet Model

```shell
iPhone 12 Pro
```

### Phone/Tablet software version

```shell
iOS Version 16.0.2
```

**Comment by dgooch5200** [comment]
@iMDJace Thank you for reporting this. We will look into this problem and let you know when we have a fix.

**Comment by dgooch5200** [comment]
should be fixed on latest build
