### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by ZevBirnbaum** [Chauvet-Pro/WELLCOM_Flarecon#7]
### Contact Details

zbirnbaum@chauvetlighting.com

### Well Com or Flarecon

Flarecon

### Is your feature request related to a problem? Please describe.

Unable to move fixtures around in the list once they have been added on the fixture page.  The added fixtures go at the bottom of the list in order added, even if the last fixture added is DMX address 1.

### Suggested solution

Would like to be able to drag fixtures up or down to visually group next to other fixtures.  Most commonly one would want to sort the list with the lowest address at the top.

### Alternative

Sort fixtures by lowest address at the top if dragging fixtures is not possible.

**Comment by dgooch5200** [comment]
We have made it, so the "Patch Fixture" page. The fixtures are sorted by the start address lowest to highest.
