### ISSUE TITLE
[Bug]: Can’t connect to FlareCon Air 

### ISSUE THREAD

**Issue by FirelandsEntertainment** [Chauvet-Pro/WELLCOM_Flarecon#9]
### Contact Details

Jeremiah@FirelandsEntertainment.com

### Well Com or Flarecon

Flarecon

### What happened?

Tested on multiple devices and unable to connect using App 2.3.1 (2) to FlareCon Air item code 03080815 ( version 2.4).

However when I test with an old version of app it connects and functions properly. 

### What Phone/Tablet are you seeing the problem on?

Apple

### Phone/Tablet Model

```shell
IPhone 13 Pro
```

### Phone/Tablet software version

```shell
IOS 16.1.1
```

**Comment by dgooch5200** [comment]
@FirelandsEntertainment Thank you for letting us know we are working on the problem.

**Comment by dgooch5200** [comment]
Now connects to Apple IOS devices with build 3.0.2.
